- name: Creates directory /etc/udev/rules.d
  file: path=/etc/udev/rules.d state=directory
- name: Install udev rules for ST-Link V2.1
  copy:
      src: files/49-stlink-v21.rules
      dest: /etc/udev/rules.d/49-stlink-v21.rules
- name: Install developer packages
  apt: name={{ item }} state=present
  with_items:
  - udev
      
- name: Force udev to reload rules
  shell: udevadm control --reload-rules || true

- name: Install gcc-arm-embedded
  apt: name=gcc-arm-none-eabi state=present
